In [2]:
############################################ 
### import festival lists
############################################ 

import os
import pandas as pd
from datetime import datetime

data_path = r"G:/My Drive/cast_and_crew/rpi/prod/interfaces/rpi10008_imdb__editor_lists/import/archive"
var_list = ("Const", "Title", "Description", "Directors", "Genres", "Release Date", "URL")

def load_festival_files(pattern, festival_name, festival_url, start_year, end_year):
    frames = []
    for year in range(start_year, end_year + 1):
        file_name = pattern.format(year=year)
        file_path = os.path.join(data_path, file_name)
        if os.path.exists(file_path):
            dfx = pd.read_csv(file_path, encoding="latin-1")
            dfx = dfx.loc[:, var_list]
            dfx["festival_name"] = festival_name
            dfx["festival_year"] = year
            dfx["festival_url"] = festival_url
            frames.append(dfx)
    result = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    result.rename(columns={"Const": "tconst"}, inplace=True)
    return result

fst = load_festival_files(
    "Cannes Film Festival {year}.csv",
    "Cannes",
    "https://www.festival-cannes.com",
    2021,
    2029,
)

fst1 = load_festival_files(
    "Yesh{year}.csv",
    "Yesh!",
    "https://www.yesh.ch/",
    2021,
    2029,
)

fst2 = load_festival_files(
    "Zurich Film Festival {year}.csv",
    "ZFF",
    "https://zff.com/en/programme/",
    2021,
    2029,
)

fst3 = load_festival_files(
    "Sundance {year} Movie Guide.csv",
    "Sundance",
    "https://festival.sundance.org/",
    2020,
    2029,
)

fst4 = load_festival_files(
    "SXSW {year} Festival Guide.csv",
    "SXSW",
    "https://www.sxsw.com/festivals/film",
    2020,
    2029,
)

fst6 = load_festival_files(
    "Toronto International Film Festival {year}.csv",
    "TIFF",
    "https://www.tiff.net/",
    2020,
    2029,
)

fst8 = load_festival_files(
    "{year} Oscars - Academy Awards predictions.csv",
    "Oscars",
    "https://www.oscars.org/oscars/ceremonies",
    2021,
    2029,
)

fst9 = load_festival_files(
    "{year} Venice International Film Festival.csv",
    "Venice",
    "https://www.labiennale.org/en/cinema/",
    2021,
    2029,
)

fst10 = load_festival_files(
    "{year} Berlin International Film Festival.csv",
    "Berlin",
    "https://www.berlinale.de/en/home.html",
    2021,
    2029,
)

fst11 = load_festival_files(
    "Karolvy Vary {year}.csv",
    "KVIFF",
    "https://www.kviff.com",
    2021,
    2029,
)



fst3 = load_festival_files(
    "Sundance {year} Movie Guide.csv",
    "Sundance",
    "https://festival.sundance.org/",
    2020,
    2029,
)

fst4 = load_festival_files(
    "SXSW {year} Festival Guide.csv",
    "SXSW",
    "https://www.sxsw.com/festivals/film",
    2020,
    2029,
)

fst6 = load_festival_files(
    "Toronto International Film Festival {year}.csv",
    "TIFF",
    "https://www.tiff.net/",
    2020,
    2029,
)

fst8 = load_festival_files(
    "{year} Oscars - Academy Awards predictions.csv",
    "Oscars",
    "https://www.oscars.org/oscars/ceremonies",
    2021,
    2029,
)

fst9 = load_festival_files(
    "{year} Venice International Film Festival.csv",
    "Venice",
    "https://www.labiennale.org/en/cinema/",
    2021,
    2029,
)

fst10 = load_festival_files(
    "{year} Berlin International Film Festival.csv",
    "Berlin",
    "https://www.berlinale.de/en/home.html",
    2021,
    2029,
)

fst11 = load_festival_files(
    "Karolvy Vary {year}.csv",
    "KVIFF",
    "https://www.kviff.com",
    2021,
    2029,
)
fst0 = load_festival_files(
    "{year} - The year in movies.csv",
    "YTD",
    "https://www.kulturinfo.ch/kino/index.html",
    2021,
    2029,
)

 
print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fst0: ', fst0.shape)
print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fst10: ', fst10.shape)
fst0.tail(3)

2026-07-10 20:20:00 fst0:  (334, 10)
2026-07-10 20:20:00 fst10:  (572, 10)

,tconst,Title,Description,Directors,Genres,Release Date,URL,festival_name,festival_year,festival_url
331,tt27817389,The Last Viking,NaN,Anders Thomas Jensen,"Comedy, Crime, Drama",2025-10-09,https://www.imdb.com/title/tt27817389/,YTD,2025,https://www.kulturinfo.ch/kino/index.html
332,tt27714581,Sentimental Value,NaN,Joachim Trier,Drama,2025-08-20,https://www.imdb.com/title/tt27714581/,YTD,2025,https://www.kulturinfo.ch/kino/index.html
333,tt35231039,Kokuho,NaN,Sang-il Lee,Drama,2025-11-21,https://www.imdb.com/title/tt35231039/,YTD,2025,https://www.kulturinfo.ch/kino/index.html

In [3]:
############################################ 
### import current screening list
############################################ 

from datetime import datetime

def load_current_screening_lists(filename, festival_name, festival_year, festival_url):
    file_path = os.path.join(data_path, filename)
    if not os.path.exists(file_path):
        return pd.DataFrame()
    df = pd.read_csv(file_path, encoding="latin-1")
    df = df.loc[:, var_list]
    df["festival_name"] = festival_name
    df["festival_year"] = festival_year
    df["festival_url"] = festival_url
    df.rename(columns={"Const": "tconst"}, inplace=True)
    return df


current_year = datetime.now().year

fstw = load_current_screening_lists(
    "whatson.csv",
    "WhatsOn",
    current_year,
    "https://www.kulturinfo.ch/kino/index.html",
)

print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fstw: ', fstw.shape)
fstw.tail(3)

2026-07-10 20:20:00 fstw:  (63, 10)

,tconst,Title,Description,Directors,Genres,Release Date,URL,festival_name,festival_year,festival_url
60,tt38776466,Kalari Kid: She Hits Back,NaN,"Maria Kaur Bedi, Satindar Singh Bedi","Documentary, Sport",2026-09-01,https://www.imdb.com/title/tt38776466/,WhatsOn,2026,https://www.kulturinfo.ch/kino/index.html
61,tt37304295,Fatherland,NaN,PaweÅ Pawlikowski,"Biography, Drama",2026,https://www.imdb.com/title/tt37304295/,WhatsOn,2026,https://www.kulturinfo.ch/kino/index.html
62,tt37510326,The Social Reckoning,NaN,Aaron Sorkin,"Biography, Drama, Thriller",2026-10-09,https://www.imdb.com/title/tt37510326/,WhatsOn,2026,https://www.kulturinfo.ch/kino/index.html

In [4]:

fst_union = pd.concat(
    [fst, fst1, fst2, fst3, fst4, fst6, fst8, fst9, fst10, fst11,  fstw, fst0],
    ignore_index=True,
)

############################################ 
### festival Union
############################################ 
# fst_union = pd.concat([fst, fst1, fst2, fst3, fst4, fst6, fst8, fst9, fst10,  fst11, fstw, fst0])
print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fst_union: ', fst_union.shape)
fst_union.tail(3)

2026-07-10 20:20:00 fst_union:  (5619, 10)

,tconst,Title,Description,Directors,Genres,Release Date,URL,festival_name,festival_year,festival_url
5616,tt27817389,The Last Viking,NaN,Anders Thomas Jensen,"Comedy, Crime, Drama",2025-10-09,https://www.imdb.com/title/tt27817389/,YTD,2025,https://www.kulturinfo.ch/kino/index.html
5617,tt27714581,Sentimental Value,NaN,Joachim Trier,Drama,2025-08-20,https://www.imdb.com/title/tt27714581/,YTD,2025,https://www.kulturinfo.ch/kino/index.html
5618,tt35231039,Kokuho,NaN,Sang-il Lee,Drama,2025-11-21,https://www.imdb.com/title/tt35231039/,YTD,2025,https://www.kulturinfo.ch/kino/index.html

In [5]:
 


fst_union ['rec_cnt'] = 1
fst_sum = fst_union.pivot_table(  index   = ( 'tconst', 'Title', 'Release Date')
                 #  , aggfunc = [  sum]     
                   , aggfunc='sum'
                   , values = [ "rec_cnt"]
                   , fill_value = 0
             )
 
fst_pivot= fst_union.pivot_table(  index   = ( 'tconst', 'Title', 'Release Date', 'festival_year')
              #     , aggfunc = [  sum]          
                   , aggfunc='sum'       
                   , values = [ "rec_cnt"]
                   , columns = [ "festival_name"]
                   , fill_value = 0
             )

In [6]:

import os

# data_path = r"G:/My Drive/cast_and_crew/rpi/prod/interfaces/rpi20003_twb__cast_and_crew/export/current/"
# output_file = os.path.join(data_path, "fst_union.csv")
data_path = r"G:/My Drive/cast_and_crew/rpi/prod/transformations/"
output_file = os.path.join(data_path, "dwh_titles__editor_lists.csv")
#output_file = os.path.join(data_path, "mrt_titles__editor_lists.csv")
fst_union.to_csv(output_file, encoding="utf-8")

print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fst_union: ', fst_union.shape)
fst_union.tail(3)

data_path = r"G:/My Drive/cast_and_crew/rpi/prod/transformations/"
output_file = os.path.join(data_path, "dwh_editor_lists__pivoted.csv")
fst_pivot.to_csv(output_file, encoding="utf-8")

print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'fst_pivot: ', fst_pivot.shape)
fst_pivot.tail(3)

2026-07-10 20:20:00 fst_union:  (5619, 11)
2026-07-10 20:20:00 fst_pivot:  (5066, 12)

                                                     rec_cnt               \
festival_name                                         Berlin Cannes KVIFF
tconst    Title           Release Date festival_year
tt9885000 Wakhri          2023-12-02   2024                0      0     0
tt9893250 I Care a Lot    2020-09-12   2021                0      0     0
tt9897230 Smiling Georgia 2023-07-04   2023                0      0     1

                                                                           \
festival_name                                        Oscars SXSW Sundance
tconst    Title           Release Date festival_year
tt9885000 Wakhri          2023-12-02   2024               0    1        0
tt9893250 I Care a Lot    2020-09-12   2021               0    0        0
tt9897230 Smiling Georgia 2023-07-04   2023               0    0        0

                                                                              \
festival_name                                        TIFF Venice WhatsOn YTD
tconst    Title           Release Date festival_year
tt9885000 Wakhri          2023-12-02   2024             0      0       0   0
tt9893250 I Care a Lot    2020-09-12   2021             0      0       0   1
tt9897230 Smiling Georgia 2023-07-04   2023             0      0       0   0


festival_name                                        Yesh! ZFF
tconst    Title           Release Date festival_year
tt9885000 Wakhri          2023-12-02   2024              0   0
tt9893250 I Care a Lot    2020-09-12   2021              0   0
tt9897230 Smiling Georgia 2023-07-04   2023              0   0