In [1]:
import pandas as pd
import numpy  as np
from datetime import datetime
#################################################
# Titles
#################################################

def conv(val):
    if not val:
        return 0    
    try:
        return np.int64(val)
    except:        
        return np.int64(0)
    
T = pd.read_csv('https://datasets.imdbws.com/title.basics.tsv.gz'
                 , compression='gzip'
                 , delimiter='\t'
                 , encoding='utf-8'
                 , header=0
                # , sep= " "
                 , quotechar='"'
                #, error_bad_lines=False
                 , dtype={ "tconst": "str" ,
                           "titleType": "str" ,
                           "primaryTitle": "str" ,
                           "originalTitle": "str" ,
                           "isAdult": "str", 
                         # "startYear":   "str" , 
                         # "endYear":   "str" ,
                           "runtimeMinutes": "str" ,
                           "genres": "str"             
                         }
                 , converters={'startYear':conv,'endYear':conv}                
                ) 
T["flg_doc"]           = np.where (T['genres'].str.contains('Documentary'),'Documentary'
                                 , np.where (T['genres'].str.contains('Animation'),'Animation','Fiction'))
T["primaryTitle_year"] = T['primaryTitle']  + ' ('+  T['startYear'].map(str)  + ')'
## filter movie 
T = T.loc[T.titleType == 'movie', :]
T = T.loc[T.startYear != 0, :]
 
print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), T.shape)

2026-07-10 20:18:00 (638490, 11)

In [2]:
# T --> cln_imdb__xref_titles_principals_filtered

import os

data_path = r"G:/My Drive/cast_and_crew/rpi/prod/transformations/"
output_file = os.path.join(data_path, "dwh_titles__details.csv")

T.to_csv(output_file, encoding="utf-8")

In [3]:
# T.tail(1000)
T[T['tconst'] == "tt1745960"].head(15)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,flg_doc,primaryTitle_year
4620567,tt1745960,movie,Top Gun: Maverick,Top Gun: Maverick,0,2022,0,130,"Action,Drama",Fiction,Top Gun: Maverick (2022)

In [4]:
#################################################
# Ratings
#################################################
R = pd.read_csv('https://datasets.imdbws.com/title.ratings.tsv.gz'
                 , compression='gzip'
                 , delimiter='\t',encoding='utf-8'
                 , header=0
                # , sep= " "
                 , quotechar='"'
                 #, error_bad_lines=False
                )

R.rename(columns = {  "averageRating": "tconst_imdb_rating"
                      , "numVotes":   "tconst_imdb_num_votes"
                      , "Const": "tconst"}
                      , inplace = True)

print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'R: ', R.shape)
R.tail(3)

2026-07-10 20:18:07 R:  (1693202, 3)

            tconst  tconst_imdb_rating  tconst_imdb_num_votes
1693199  tt9916850                 6.0                      7
1693200  tt9916852                 5.7                      7
1693201  tt9916880                 7.6                     11

In [5]:
# n --> cln_imdb__xref_titles_principals_filtered

import os

data_path = r"G:/My Drive/cast_and_crew/rpi/prod/transformations/"
output_file = os.path.join(data_path, "dwh_titles__ratings.csv")

R.to_csv(output_file, encoding="utf-8")